name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight (UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_1a164acc-8446-4936-bd72-dfb477fc730d}}
